# -*- coding: utf-8 -*-
"""Mohammed_Alrashidan_homework1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FbI-k5_5N-qJIrvqSUOdUhJFRpc-oAXP
    https://colab.research.google.com/drive/1FbI-k5_5N-qJIrvqSUOdUhJFRpc-oAXP?usp=sharing
# Homework 1 (20 points)

**The very first thing you should do is save your own copy of this Homework by clicking on File -> "Save a copy in Drive"**

This homework is divided into 3 sections which all perform different tasks on the initial data provided.  Read the data description below carefully to understand the data, then work on each section.

When you complete this assignment, **please submit 2 files via Canvas before the deadline.**


1.   Your Jupyter Notebook code as a .py file (File -> "Download .py")
2.   A PDF of all of your code/output in this Jupyter Notebook (File -> Print -> Save as PDF)

Please use the naming convention:

**firstname_lastname_homework1.py**

**firstname_lastname_homework1.pdf**

## Data Description

The data below represents average daily temperatures for the month of August 2000 are provided below for 7 major European cities.  Thus, each city-named variable is assigned a list of 31 values, one for every day in the month of August.  They are sequential, so the first value represents the average daily temperature on August 1 and the last value represents the average daily temperature on August 31.

In other words, the data format is:

`city_name = [august1_temp, august2_temp, ... , august31_temp]`

Run the code block to load the data.  Then use this data to answer questions 1 and 2.
"""

# Each data point represents one day in the month of August 2000.
# e.g. the first data point was the avg daily temperature on August 1, 2000
paris =      [75.9, 67.2, 64.2, 63.3, 65.5, 67.0, 70.3, 68.1, 70.9, 68.0, 69.9, 74.0, 77.1, 74.1, 70.0, 69.8, 69.9, 67.9, 65.9, 63.3, 62.4, 63.8, 68.6, 73.3, 75.8, 70.7, 63.5, 64.6, 66.4, 66.4, 65.3]
helsinki =   [60.2, 62.1, 61.7, 61.7, 60.2, 62.7, 61.9, 58.6, 56.8, 59.8, 59.9, 61.8, 63.0, 63.9, 60.1, 64.5, 59.5, 57.4, 60.3, 60.2, 60.4, 58.9, 54.6, 54.3, 57.2, 58.9, 58.5, 59.0, 59.2, 61.1, 60.9]
copenhagen = [61.2, 62.4, 60.6, 60.6, 59.0, 61.5, 57.6, 57.5, 58.8, 57.5, 60.5, 59.5, 58.6, 61.7, 65.5, 60.6, 60.2, 60.5, 60.3, 60.9, 57.4, 56.2, 56.3, 55.9, 57.9, 58.4, 62.0, 61.0, 61.8, 57.6, 55.5]
rome =       [73.9, 73.5, 73.6, 75.2, 71.8, 70.0, 71.4, 73.7, 73.3, 74.5, 74.9, 74.4, 79.5, 76.0, 76.8, 78.3, 77.1, 77.4, 76.4, 77.2, 77.9, 78.7, 79.6, 79.9, 77.6, 78.4, 77.8, 77.4, 76.5, 73.8, 74.9]
madrid =     [83.8, 83.8, 73.6, 67.9, 68.0, 70.5, 73.2, 75.0, 78.7, 81.2, 76.7, 74.8, 78.7, 78.7, 84.6, 83.9, 83.6, 82.3, 79.3, 75.7, 73.6, 68.6, 68.8, 73.9, 76.0, 71.9, 71.8, 73.8, 77.3, 75.9, 71.7]
stockholm =  [65.9, 62.7, 60.5, 63.9, 63.9, 63.9, 61.0, 58.1, 62.5, 63.1, 64.1, 63.6, 61.3, 64.4, 65.3, 63.6, 62.6, 62.1, 63.3, 60.3, 61.1, 59.4, 57.5, 54.7, 57.0, 61.4, 62.1, 62.4, 62.7, 61.0, 56.5]
london =     [66.6, 63.1, 61.3, 63.9, 65.1, 68.7, 68.0, 66.8, 65.4, 67.8, 67.6, 68.8, 65.9, 67.6, 65.6, 65.6, 63.0, 62.2, 64.9, 63.4, 60.8, 62.4, 64.8, 67.8, 68.3, 65.7, 61.5, 60.4, 61.2, 62.3, 61.1]

"""## Section 1 - Summary Stats

Value: 5 points (1 point for each correct answer)

Using `numpy` load the data into `numpy` arrays. Include the code as well as the answers.

1.   What are the mean, min, and max temperatures of Paris?
2.   What is the minimum and maximum temperature in Europe (from the 7 cities provided) for the month of August?
3.   Which city had the greatest range of temperatures in August (max - min)?  What was it?
4.   Which city had the smallest range of temperatures in August (max - min)?  What was it?
5.   Output an array with the daily average temperature of the 7 cities for the month.  The resulting array should have 31 elements in it, one for each day, with each data point representing the mean of the 7 daily temperatures for that day.
"""

# 1 Write code and answer below
import numpy as np

paris_stat = np.array([paris]) # create an array for paris
mean = np.mean(paris_stat) # to get the mean
min = np.min(paris_stat)   #  to get the min
max = np.max(paris_stat)   # to get the max

print("The Mean of the temperature in Paris is: " + str(round(mean, 2)))
print("The Min of the temperature in Paris is: " + str(round(min, 2)))
print("The Max of the temperature in Paris is: " + str(round(max, 2)))

# 2 Write code and answer below
euro_cities = np.array([paris, helsinki, copenhagen, rome, madrid, stockholm, london])

# to get the max
print("The Maximum Temperature in Europe is: "+ str(np.max(euro_cities)))

#to get the min
print("The Maximum Temperature in Europe is: "+ str(np.min(euro_cities)))



#print(euro_cities)

# 3 Write code and answer below

city_ranges = []

for city in euro_cities:
  for temper in city:
    min = np.min(city)
    max = np.max(city)
    range = max - min
  city_ranges.append(round(range, 2))


print(city_ranges)
print("The Greatest Range is Madrid with Range of: " + str(np.max(city_ranges)))

# 4 Write code and answer below
print(city_ranges)
print("The Smallest Range is London with Range of: " + str(np.min(city_ranges)))

# 5 Write code and answer below

temp =np.sum(euro_cities, axis=0)
avg_temp = temp / 7

for x in enumerate(avg_temp, 1): # to show number of days
  avgg = np.round(x,2)
  print((avgg))

"""## Section 2 - Data Transformation
**Value: 10 points total**

**Part 1 (3 points)**
Numbers are useful, but sometimes we can extract more insight from data if we find a way to group or categorize the numbers in a meaningful way.  For the temperature data, let's group this data into temperature categories as defined below.

---


80+ degrees: "Hot"

70 <= x < 80 degrees:  "Warm"

60 <= x < 70 degrees:  "Cool"

Less than 60 degrees:  "Cold"


---


**Pick one city**, iterate through the temperature array and create a new array or list that contains the categories above based on the avg daily temperature.

The output should thus be an array (or list) that has 31 elements.  Each element is a string that is either `"Hot"`, `"Warm"`, `"Cool"` or `"Cold"`. Let's name this new array `cityname_temperature_categories` where `cityname` should be replaced with the city you chose.

Example:  The first few values of `paris_temperature_categories` would be `["Warm", "Cool", "Cool", "Cool" ... ]`

*Hint: Use `if` and `elif` statements combined with one or more `for` loops.*

*Challenge: For a challenge (not required), find a way to scale your transformation solution to all 7 cities, perhaps using loops or functions*
"""

# Write code below.

any_city = np.array(city)
list_city = []

def any_temp(city):
  for temp in city:
    if temp  >= 80:
      list_city.append("Hot")
    elif temp >= 70 and temp < 80:
      list_city.append("Warm")
    elif temp >= 60 and temp < 70:
      list_city.append("Cool")
    else:
      list_city.append("Cold")
  return list_city

any_temp(paris) # type any city in parameter

print(list_city)
# Print your output array below

"""**Part 2 (4 points)**

Suppose we want to better understand how the temperatures fluctuate from day to day.  **Pick one city (can be the same city as part 1)** and let's create a new array (or list) that measures the delta between the temperature on **day** and **day+1**.

This should result in a an array/list with 30 elements in it.  The first element (at index 0) would be the temperature delta August 2 - August 1, the second element (at index 1) would be August 3 - August 2, and so on until the final element is August 31 - August 30. Let's name this new array `cityname_daily_deltas` where `cityname` should be replaced with the city you chose.

Example: The first few values of `paris_daily_deltas` would be `[-8.7, -3. , -0.9,  2.2 ... ]`


*Hint:  There are multiple ways to accomplish this. Feel free to choose whichever way you are most comfortable with.  One way could involve creating a new list by looping through the original list.  Another way could involve copying and slicing arrays, then element-wise subtracting.*

*Challenge: For a challenge (not required), find a way to scale your transformation solution to all 7 cities, perhaps using loops or functions*
"""

# Write code below.
city_daily_deltas = []


def city_delta(city):
  n = 0
  x = 1
  for d in city:
    if x <  31:
      delta = np.array(city[x])-np.array(city[n]) # to get the delta we substract x-n where x > n
      n += 1 # if n increases by a day x increase +1day
      x += 1
      city_daily_deltas.append(round(delta, 2)) #  store the calculated delta for each day
  print(city_daily_deltas)


city_delta(madrid) # choose a city to get its delta. *** any typed city will reflect on part 3 too.

print(len(city_daily_deltas)) # test for 30 elementes

"""**Part 3 (3 points)**

Now, we want to translate the deltas in the delta arrays we created in Part 2 from numeric values into text categories.  Using the following definitions, create new arrays (or lists) that contain the given text string translation of the numeric value.

The result should be an arrays with 30 elements, as we are simply transforming the numeric values into text categories. Let's name this new array `cityname_daily_delta_categories` where `cityname` should be replaced with the city you chose in part 2.

Example: The first few values of `paris_daily_delta_categories` would be ["large_decrease", "small_decrease" , "no_significant_change", "small_increase" ... ]

---


x >= 7     : "large_increase"

3 <= x < 7 : "medium_increase"

1 <= x < 3 : "small_increase"

-1 <= x < 1 : "no_significant_change"

-3 <= x < -1 : "small_decrease"

-7 <= x < -3 : "medium_decrease"

x < -7       : "large_decrease"


---

*Challenge: For a challenge (not required), find a way to scale your transformation solution to all 7 cities, perhaps using loops or functions*
"""

# Write your code below.

# run part 2 first and make sure to choose a city. This code will be reflected based on what city you choose from part 2

city_d = print(city_daily_deltas)

city_daily_categories = [] # store categories based on any city chosen from part 2

def city_catg():
  for catg in city_daily_deltas:
    if catg >= 7:
      city_daily_categories.append("large_increase")
    elif catg >= 3 and catg < 7:
      city_daily_categories.append("medium_increase")
    elif catg >= 1 and catg < 3:
      city_daily_categories.append("small_increase")
    elif catg >= -1 and catg < 1:
      city_daily_categories.append("no_significant_change")
    elif catg >= -3 and catg < -1:
      city_daily_categories.append("small_decrease")
    elif catg >= -7 and catg < -3:
      city_daily_categories.append("medium_decrease")
    else:
      city_daily_categories.append("large_decrease")
  return city_daily_categories

city_catg()
print(len(city_daily_categories), city_daily_categories) # len is to make sure this is a 30 days of changes

"""## Section 3 - Histogram
**Value: 5 points (2 points for writing the function, 3 points for passing all test cases)**

Write a **function** to create a histogram (a frequency distribution) of an arbitrary list of input values.  The function will take in as input a **list** of values, and return a dictionary with **keys** representing each value in the input list and **values** representing the frequency with which they appear in the input list.

For example, given input `["M", "F", "F", "F, "M"]`, the function should return `{"M": 2, "F": 3}` as there are two "M" and three "F" in the input list.

*Hint:  For every value you process, you will need to consider whether you need to add a new key to the output dictionary `histogram` or increment the stored count for an existing key.*
"""

def create_histogram(input_list):
    histogram = {}
    for a in input_list:
      if a in histogram:
        histogram[a] += 1
      else:
        histogram[a] = 1

    # fill in your code below
    # then execute this code block to define the function

    return histogram

# Below are a few test cases. Don't modify the code below. Simply run this code block.
# If you get an assertion error, this means that at least one of the test cases is failing.
# If it gets to the print statement, this means that all tests have passed

assert(create_histogram([1,1,1,1,1,1,1,1,1,2]) == {1:9, 2:1})
print("Passed first test case")
assert(create_histogram(["black", "blue", "yellow", "black", "blue", "red", "", "green"]) == {'': 1, 'black': 2, 'blue': 2, 'green': 1, 'red': 1, 'yellow': 1})
print("Passed second test case")
assert(create_histogram([l for l in "how many of each letter are in this sentence"]) ==
{' ': 8,
 'a': 3,
 'c': 2,
 'e': 7,
 'f': 1,
 'h': 3,
 'i': 2,
 'l': 1,
 'm': 1,
 'n': 4,
 'o': 2,
 'r': 2,
 's': 2,
 't': 4,
 'w': 1,
 'y': 1})
print("Passed third test case")
print("Passes all tests")

"""**Putting it all together**

Try running your new `create_histogram` function on the arrays you created from Section 2 to see the frequency distribution of the categories you defined.

*Side Note: If you took the challenge to scale your solutions to all 7 cities, it would be especially interesting to compare the relative distributions of the temperature categories and delta categories across cities.*
"""

# Pass the arrays you created in Section 2 into your `create_histogram` function
print(create_histogram(city_daily_deltas))
print(create_histogram(city_daily_categories))
